name: CivitasCraft

main: io.github.squishy453.civitasCraft.CivitasCraft

version: '1.0-SNAPSHOT'

api-version: '1.21'

author: Squishy453

commands:
  civitas:
    description: Main command for CivitasCraft
    usage: /<command>
    permission: civitas.use

  ban:
    description:
    usage: /ban <player> [reason] [duration]
    permission: civitas.owner

permissions:
  civitas.owner:
    description: Allows use of Owner commands.
    default: false

  civitas.use:
    description: Allows use of /civitas
    default: true

load: STARTUP
